### ISSUE TITLE
How to run multiple instances on Maxwell on same MySQL DB?

### ISSUE THREAD

**Issue by GitSpree23** [zendesk/maxwell#1740]
I'm setting up prod & dev instances for my app that uses Maxwell.

This is my docker-compose:

```
version: "3.2"
services:
  maxwell:
    image: zendesk/maxwell
    container_name: ct_maxwell
    restart: always
    command: " bin/maxwell --user='binLogReaderMaxwell' --password='binLogReaderMaxwell' --host='my-rds.net' 
    --replica_server_id=232323232323 --client_id='ct_dev' --schema_database='binLogReaderMaxwell'
    --filter='exclude: *.*, include: mydb.users, include:mydb.transactions'  --producer=rabbitmq --rabbitmq_user='admin' 
    --rabbitmq_pass='rabbitmqproject' --rabbitmq_host='x.x.x.x' --rabbitmq_port=5670 --rabbitmq_virtual_host='myvhost' 
    --rabbitmq_exchange='maxwell' --rabbitmq_exchange_type='direct' --rabbitmq_routing_key_template='maxwell' 
    --rabbitmq_exchange_durable='true' --rabbitmq_message_persistent='true'"
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "10"
```

How do I create two instances without any data loss?
