### ISSUE TITLE
maxwell docker image no longer works in circle ci

### ISSUE THREAD

**Issue by drupsys** [zendesk/maxwell#1811]
I am tried to upgrade our maxwell daemon version to latest (from v1.33.1 to v1.35.5) and even though everything works fine in development but our circle ci pipelines are broken.

You can use the following ci job to replicate the issue

```
  temp:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Demo if the issue
          command: |
            docker run -d --name binlog-parser --restart on-failure zendesk/maxwell:v1.35.5 /bin/bash -c "bin/maxwell"
            docker logs binlog-parser
```

I've done a little bit of investigation into the issue and from what I can tell something bad is happening to the file system permissions inside container, if you run `ls -l` in the container you get the following output.

```
29521cea6aa3:/app# docker run -it --name binlog-parser --restart on-failure zendesk/maxwell:v1.35.5 ls -l
ls: cannot access 'README.md': Operation not permitted
ls: cannot access 'bin': Operation not permitted
ls: cannot access 'kinesis-producer-library.properties.example': Operation not permitted
ls: cannot access 'config.properties.example': Operation not permitted
ls: cannot access 'lib': Operation not permitted
ls: cannot access 'config.md': Operation not permitted
ls: cannot access 'LICENSE': Operation not permitted
ls: cannot access 'log4j2.xml': Operation not permitted
ls: cannot access 'quickstart.md': Operation not permitted
total 0
-????????? ? ? ? ?            ? LICENSE
-????????? ? ? ? ?            ? README.md
d????????? ? ? ? ?            ? bin
-????????? ? ? ? ?            ? config.md
-????????? ? ? ? ?            ? config.properties.example
-????????? ? ? ? ?            ? kinesis-producer-library.properties.example
d????????? ? ? ? ?            ? lib
-????????? ? ? ? ?            ? log4j2.xml
-????????? ? ? ? ?            ? quickstart.md
```

You get the same sort of output no matter what folder you run `ls` in, so it looks like os is unable to get file permissions for the file system somehow, nothing I've tried solve the issue.
