### ISSUE TITLE
maxwell-bootstrap blocks without errors.

### ISSUE THREAD

**Issue by zjd-melo** [zendesk/maxwell#2015]
I use docker-compose run mysql and maxwell, i want to bootstrap a table, but come with some problems. needs help.

### Docker-compse
```
version: "3"
services:
  mysql_maxwell:
    container_name: mysql_maxwell
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sqlpwd
      MYSQL_PASSWORD: sqlpwd
    volumes:
      - ./volumes/mysql/conf/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  maxwell:
    image: zendesk/maxwell:v1.40.2
    container_name: maxwell
    command: bin/maxwell --config /etc/maxwell/config.properties
    volumes:
      - ./volumes/maxwell:/etc/maxwell/
      
  maxwell-bootstrap:
    image: zendesk/maxwell:v1.40.2
    container_name: maxwell-bootstrap
    command: bin/maxwell-bootstrap  --database test --table t3 --user root --password sqlpwd --host mysql_maxwell \
             --port 3306 --log_level DEBUG --client_id test --config /etc/maxwell/config.properties
    volumes:
      - ./volumes/maxwell:/etc/maxwell/
```
### Mysqld conf
```
[mysqld]
pid-file	        = /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
datadir		= /var/lib/mysql
#log-error	= /var/log/mysql/error.log
symbolic-links=0
server-id=110
log-bin=/var/lib/mysql/mysql-bin
binlog-format=ROW
```

### Maxwell config
```
producer=stdout
log_level=DEBUG
host=mysql_maxwell
port=3306
user=root
password=sqlpwd
schema_database=maxwell
client_id=test
```
### Question one
There only `test` database in mysql, when i up `maxwell-bootstrap` docker service, it says `Table 'maxwell.bootstrap' doesn't exist`.
Should i create maxwell meta tables first or there are other ways to generate those maxwell tables?

### Question two
After i up `maxwell` docker service, it auto create maxwell db and related tables, and maxwell behaves well, it captured changes.
So i stopped `maxwell`docker service and up  `maxwell-bootstrap` docker service, it blocked, the logs as follows
```
➜  services docker-compose up maxwell-bootstrap 
Starting maxwell-bootstrap ... done
Attaching to maxwell-bootstrap
maxwell-bootstrap    | connecting to jdbc:mysql://mysql_maxwell:3306/maxwell?allowPublicKeyRetrieval=true&connectTimeout=5000&zeroDateTimeBehavior=convertToNull
maxwell-bootstrap    | 2023-06-20 09:06:13 INFO  MaxwellBootstrapUtility - counting rows
maxwell-bootstrap    | 2023-06-20 09:06:14 INFO  MaxwellBootstrapUtility - inserting bootstrap start row
```
A row was inserted to maxwell.bootstrap, but it does not prints event to `stdout`.

Can anyone help me.
