### ISSUE TITLE
Running maxwell on kubernetes

### ISSUE THREAD

**Issue by KURANADO2** [zendesk/maxwell#2036]
I want running maxwell on kubernets.

Below is my `raft.xml` file:

```xml
<?xml version='1.0' encoding='utf-8'?>
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    <UDP mcast_addr="228.8.8.8" mcast_port="${jgroups.udp.mcast_port:45588}"/>
    <PING />
    <MERGE3 />
    <FD_SOCK/>
    <FD_ALL/>
    <VERIFY_SUSPECT timeout="1500"/>
    <pbcast.NAKACK2 xmit_interval="500"/>
    <UNICAST3 xmit_interval="500"/>
    <pbcast.STABLE desired_avg_gossip="50000" max_bytes="4M"/>
    <raft.NO_DUPES/>
    <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
    <UFC max_credits="2M" min_threshold="0.4"/>
    <MFC max_credits="2M" min_threshold="0.4"/>
    <FRAG2 frag_size="60K"/>
    <raft.ELECTION election_min_interval="500" election_max_interval="1000" heartbeat_interval="250"/>
    <raft.RAFT members="A,B,C" raft_id="${raft_id:undefined}"/>
    <raft.REDIRECT/>
</config>
```

Below is my kubernetes deploy yaml file: `maxwell.yaml`

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: maxwell
  namespace: abup
#  annotations:
#    nginx.ingress.kubernetes.io/affinity: "true"
#    nginx.ingress.kubernetes.io/session-cookie-name: backend
#    nginx.ingress.kubernetes.io/load-balancer-method: drr
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: maxwell
  ports:
  - name: web
    port: 7800
    targetPort: 7800
    nodePort: 30111
---
apiVersion: v1
kind: Service
metadata:
  name: maxwell-headless
  namespace: abup
  labels:
    app: maxwell
spec:
  ports:
    - port: 7800
      name: server
      targetPort: 7800
  clusterIP: None
  selector:
    app: maxwell
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
#  labels:
#    k8s-app: maxwell
#    qcloud-app: maxwell
  name: maxwell
  namespace: abup
spec:
  serviceName: maxwell-headless
  replicas: 3
  selector:
    matchLabels:
      k8s-app: maxwell
      qcloud-app: maxwell
#  strategy:
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 0
#    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: maxwell
        qcloud-app: maxwell
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: 
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - 10.19.10.13
              - 10.19.10.2
              - 10.19.10.7
```

Content of the `maxwell.sh` script in the yaml file:

```bash
#!/bin/bash
hostname=$(cat /etc/hostname)
if [ $hostname = maxwell-0 ]
   then
     ./bin/maxwell --producer_partition_by=table --config /etc/maxwell/config.properties --ha --raft_member_id=A
   elif [ $hostname = maxwell-1 ]
        then
          ./bin/maxwell --producer_partition_by=table --config /etc/maxwell/config.properties --ha --raft_member_id=B
   elif [ $hostname = maxwell-2 ]
        then
          ./bin/maxwell --producer_partition_by=table --config /etc/maxwell/config.properties --ha --raft_member_id=C
   else
        echo "No Matched" > test.txt
fi
```

When i execute command: `kubectl apply -f maxwell.yaml`, The logs for the three Pods are as follows:

<img width="1511" alt="image" src="https://github.com/zendesk/maxwell/assets/20608930/151efe34-b378-4ac0-aede-db6fc9ec142b">

What should I do to get the three nodes to start an election?
